### ISSUE TITLE
中文咨询

### ISSUE THREAD

**Issue by Leo-zhanglj** [infrastlabs/docker-headless#1]
你好，
请问一下，容器启动后安装了wps，rdp连接之后，桌面无法查看中文，wps也无法输入中文，请问如何解决？

**Comment by huapox** [comment]
你好，

- 1.环境指定中文：

`docker run -it --rm --shm-size 1g -e VNC_OFFSET=20 -e L=zh_CN --net=host infrastlabs/docker-headless:full`  

(注：`-e L=zh_CN`指定语言环境, full镜像才支持多语言)

- 2.输入法中文： 鼠标左点击输入法的trayIcon > 部署。 即可使用

**Comment by Leo-zhanglj** [comment]
> 你好， 1.环境指定中文：`docker run -it --rm --shm-size 1g -e VNC_OFFSET=20 -e L=zh_CN --net=host infrastlabs/docker-headless:full` -e L=zh_CN, full镜像才支持多语言 2.输入法中文： 鼠标左点击输入法的trayIcon > 部署。 即可使用

root@ldap:~# docker run -it --rm --shm-size 1g -e VNC_OFFSET=20 -e L=zh_CN --net=host infrastlabs/docker-headless:full -e L=zh_CN
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "-e": executable file not found in $PATH: unknown.

**Comment by huapox** [comment]
`docker run -it --rm --shm-size 1g -e VNC_OFFSET=20 -e L=zh_CN --net=host infrastlabs/docker-headless:full`

**Comment by Leo-zhanglj** [comment]
> `docker run -it --rm --shm-size 1g -e VNC_OFFSET=20 -e L=zh_CN --net=host infrastlabs/docker-headless:full`

测了一下，好像宿主的默认语言是中文的话，不加环境变脸也可以感知到中文。
谢谢。

**Comment by Leo-zhanglj** [comment]
resolved！

**Comment by huapox** [comment]
**(2)使用帮助**: 

- [云桌面功能简介](https://github.com/infrastlabs/docker-headless/blob/dev/docs/01-CloudDesktop.md)
- [1.如何设置为中文或其它语言？](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b0-locale.md)
- [2.双屏连接，远程剪切板、音频如何使用？](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b1-rdp.md)
- [3.如何WEB访问远程桌面？](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b2-vnc.md)
- [4.中文输入法、截图软件的使用说明](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b3-apps.md)
- [Detail明细说明](https://github.com/infrastlabs/docker-headless/blob/dev/detail.md) （快捷键、环境变量、系统应用）

---
如上链接，详见根目录下README.md

**Comment by Leo-zhanglj** [comment]
> **(2)使用帮助**:
> 
> * [云桌面功能简介](https://github.com/infrastlabs/docker-headless/blob/dev/docs/01-CloudDesktop.md)
> * [1.如何设置为中文或其它语言？](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b0-locale.md)
> * [2.双屏连接，远程剪切板、音频如何使用？](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b1-rdp.md)
> * [3.如何WEB访问远程桌面？](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b2-vnc.md)
> * [4.中文输入法、截图软件的使用说明](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b3-apps.md)
> * [Detail明细说明](https://github.com/infrastlabs/docker-headless/blob/dev/detail.md) （快捷键、环境变量、系统应用）
> 
> 如上链接，详见根目录下README.md



> **(2)使用帮助**:
> 
> * [云桌面功能简介](https://github.com/infrastlabs/docker-headless/blob/dev/docs/01-CloudDesktop.md)
> * [1.如何设置为中文或其它语言？](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b0-locale.md)
> * [2.双屏连接，远程剪切板、音频如何使用？](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b1-rdp.md)
> * [3.如何WEB访问远程桌面？](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b2-vnc.md)
> * [4.中文输入法、截图软件的使用说明](https://github.com/infrastlabs/docker-headless/blob/dev/docs/b3-apps.md)
> * [Detail明细说明](https://github.com/infrastlabs/docker-headless/blob/dev/detail.md) （快捷键、环境变量、系统应用）
> 
> 如上链接，详见根目录下README.md

尝试在windows和mac的docker desktop上部署这个，好像都不能正常工作，10089端口无法telnet，启动报错，请问是不是这个产品只能部署在Linux上的docker上。

**Comment by huapox** [comment]
**(3)Producttion-Deployment**: 

- [Windows-VM Deployment：](https://github.com/infrastlabs/docker-headless/blob/dev/deploy/virtualbox/README.md) With `barge-os` mini-container system, `--net=host` Use the VM's IP 
- [Linux-Server Deployment：](https://github.com/infrastlabs/docker-headless/blob/dev/deploy/fat-docker/README.md) Use `macvlan`'s network，with special IP，sugest with lxcfs installed.
- [Kubernetes Deployment：](https://github.com/infrastlabs/docker-headless/blob/dev/deploy/kubernetes/README.md) StatefulSet(TODO)

**Comment by Leo-zhanglj** [comment]
按照文档 2.输入法中文： 鼠标左点击输入法的trayIcon > 部署。 即可使用，依然无法切换出中文输入法，按照搜狗拼音输入法后进行配置也无法使用中文输入。
请问该这个输入法如何才能切换出来并且使用中文呢？

**Comment by Leo-zhanglj** [comment]
![1645596762(1)](https://user-images.githubusercontent.com/18610058/155269962-92443f78-e9d7-4973-b708-e8382724f0e7.png)
按照文档也部署了，可是无法切换出输入中文的提示

**Comment by huapox** [comment]
> ![1645596762(1)](https://user-images.githubusercontent.com/18610058/155269962-92443f78-e9d7-4973-b708-e8382724f0e7.png) 

---
alt+e 打开geany编辑器试试， 

- shift: 切换中英文
- f4: rime输入法选择

**Comment by Leo-zhanglj** [comment]
> > ![1645596762(1)](https://user-images.githubusercontent.com/18610058/155269962-92443f78-e9d7-4973-b708-e8382724f0e7.png)
> 
> alt+e 打开geany编辑器试试，
> 
> * shift: 切换中英文
> * f4: rime输入法选择

alt+e 打开geany编辑器试试，这个是可以输入中文，但是wps就不行，怎么切换都切换不出来。

**Comment by huapox** [comment]
```bash
# ibus support with wps
sudo sed -i "1a export XMODIFIERS=@im=ibus" /usr/bin/{wps,wpp,et}
sudo sed -i "2a export QT_IM_MODULE=ibus" /usr/bin/{wps,wpp,et}
```

**Comment by Leo-zhanglj** [comment]
> ```shell
> # ibus support with wps
> sudo sed -i "1a export XMODIFIERS=@im=ibus" /usr/bin/{wps,wpp,et}
> sudo sed -i "2a export QT_IM_MODULE=ibus" /usr/bin/{wps,wpp,et}
> ```

测试可以，wps下采用ibus可以完成中文输入了，谢谢。

又测试了一下搜狗输入法，安装都正常，但是即使在切换到搜狗输入法下，搜狗输入法也无法生效。看了一下docker镜像的版本是debian 9的，不知道楼主有没有测试过ibus之外的输入法是否可以工作，谢谢。

**Comment by Leo-zhanglj** [comment]
楼主可否留个邮件地址或者其他及时通讯软件账号，想具体了解一下这产品，不知是否方便？

**Comment by Leo-zhanglj** [comment]
![image](https://user-images.githubusercontent.com/18610058/155960236-bdc37c1b-5c03-40b1-9110-7d1405b8c8ad.png)
虽然多种输入法都安装上了，可是无法产生中文输入，在 ALT + E 文本编辑器也不行。
