### ISSUE TITLE
RDP客户端连接做磁盘映射后在/home/headless/thinclient_drives/目录下没有挂载的磁盘

### ISSUE THREAD

**Issue by 350227036** [infrastlabs/docker-headless#10]
![image](https://github.com/infrastlabs/docker-headless/assets/25679758/450af53a-fb43-4a0e-be3d-f5efc26b26a8)

除了在连接时勾选本地资源的驱动器，在服务器上还要做配置吗，使用的是最新版镜像

**Comment by huapox** [comment]
![图片](https://github.com/infrastlabs/docker-headless/assets/6138651/3e061ab7-41a5-4533-9744-cd86eaaeb251)

**Comment by huapox** [comment]
如图

- find /tmp/.xrdp 确保其内有socket
- sudo sv status |grep chansrv 确保进程正常运行

最新版（前两天）的改动：

1、改用go-supervisor(sv)做进程管理  
2、chansrv独立有sv管理进程，免`xrdp-chansrv &`运行方式，导致进程运行一阵后挂掉无法再拉起

**Comment by 350227036** [comment]
> 
如图所示检查了配置，用了新工具连接，还是没有挂载硬盘。我已经更新到了最新的镜像
![image](https://github.com/infrastlabs/docker-headless/assets/25679758/2e576520-3f71-42ab-b53f-f35e42fa8d3e)

**Comment by huapox** [comment]
容器是如何运行的呢(命令或docker-compose.yml模板)， 挂盘需指定`--privileged`

**Comment by 350227036** [comment]
> 容器是如何运行的呢(命令或docker-compose.yml模板)， 挂盘需指定`--privileged`

加了该选项创建，使用mRemoteNG连接可以挂载了。
但是使用win10自带的mstsc.exe远程挂载不了。和上图一样，没发现硬盘

**Comment by huapox** [comment]
> “但是使用win10自带的mstsc.exe远程挂载不了。和上图一样，没发现硬盘”

请自行再检查下环境， 另挂盘注意项如下：

- 要求特权模式 (命令或docker-compose.yml模板)， 挂盘需指定`--privileged`
- 关注chansrv程序是否正常运行（新版采用go-supervisor管理做保活）

```bash
headless @ zm4210 in ~/Desktop |14:14:59  
$ sudo sv status
ssh                              Running   pid 124, uptime 0:28:05
webvnc                           Running   pid 130, uptime 0:28:05
x11-chansrv                      Running   pid 137, uptime 0:28:05
x11-de                           Running   pid 129, uptime 0:28:05
x11-parec                        Running   pid 133, uptime 0:28:05
x11-pulse                        Running   pid 126, uptime 0:28:05
x11-xvnc                         Running   pid 144, uptime 0:28:05
xrdp                             Running   pid 147, uptime 0:28:05
headless @ zm4210 in ~/Desktop |14:19:04  
$ #sudo sv restart x11-chansrv
headless @ zm4210 in ~/Desktop |14:19:28  
$ #sudo sv shutdown

#如上可用sudo sv restart x11-chansrv重启该进程，或sudo sv shutdown直接重启整个容器  （x11中的11对应`VNC_OFFSET`）
```

chansrv正常且xrdp连接上来后，有如下信息


```bash
headless @ zm4210 in ~/Desktop |14:21:09  
$ find /tmp/ |grep chans
/tmp/.xrdp/xrdp_chansrv_audio_out_socket_11
/tmp/.xrdp/xrdp_chansrv_audio_in_socket_11
```
