### ISSUE TITLE
Would it be deployed to Fedora39 for the the same headless? The sound delayed about 10-15 seconds.

### ISSUE THREAD

**Issue by gmicroul** [infrastlabs/docker-headless#14]
Would it be deployed to Fedora39 for the the same headless? The sound delayed about 10-15 seconds.

**Comment by huapox** [comment]
try xrdp with mstsc.exe

**Comment by gmicroul** [comment]
delayed 5 seconds

**Comment by huapox** [comment]
/closed and explain:

Pulseaudio with [pulseaudio-module-xrdp](https://github.com/neutrinolabs/pulseaudio-module-xrdp) plugin is a near real time solution.

When use it with `mstsc` in RDP mode and the Box/Client in the same Lan, will got the best sound effect(clear and few latency)

Current two type entry

- RDP (when in internet mode, we can turn with lower color-bits for fruent bandwidth)
  - `mRemouteNG/mstsc > xrdp> xrdp-pulse > pulseaudio` for sound ([pulseaudio-module-xrdp](https://github.com/neutrinolabs/pulseaudio-module-xrdp) Already choosed v0.5 for fewer latency but will drop/lost part audio when overstock, v0.6 without lost part audio when overstock but with more latency)
  - `mRemouteNG/mstsc > xrdp> tigerVNC` for screen
- noVNC
  - `noVNC> websocket> broadcast-server> parec> pulseaudio` for audio (with more latency with [broadcast-server](https://github.com/schollz/broadcast-server))
  - `noVNC> websocket> tigerVNC` for screen
