### ISSUE TITLE
Can this use mpv + yt-dlp ?

### ISSUE THREAD

**Issue by gmicroul** [infrastlabs/docker-headless#16]
want to use it to play online video. but seems yt-dlp not be used by mpv(version old).

**Comment by huapox** [comment]
You can with a try, if latest tag(`ubt-custom`), notice this(a drop of libLLVM-12.so, for slim size):

https://github.com/infrastlabs/docker-headless/blob/dev/ubt-custom/src/Dockerfile#L31C3-L31C50

```bash
  # LLVM(定制版这里删调它,除gnome,cinna其它de无影响); clear big lib: 88M (qt: flameshot,sogoupinyin) > img: -27M
  rm -f /usr/lib/x86_64-linux-gnu/libLLVM-12.so.1; \
  rm -f /usr/lib/aarch64-linux-gnu/libLLVM-12.so.1; 
```

**Comment by gmicroul** [comment]
arch-kde can be, just install mpv yt-dlp together then working.
