### ISSUE TITLE
可不可以更新一个ubuntu22.04

### ISSUE THREAD

**Issue by animeic** [infrastlabs/docker-headless#17]
用了很长时间了，挺好用的。希望升级一下系统。

**Comment by huapox** [comment]
见 tag `infrastlabs/docker-headless:ubuntu-22.04`

- 可关注 https://github.com/infrastlabs/docker-headless/tree/dev/distros
- 明细TAG列表 https://github.com/infrastlabs/docker-headless/blob/dev/Detail.md#%E4%B8%80tags

**Comment by animeic** [comment]
好的，谢谢。
