### ISSUE TITLE
can't copy/paste files.

### ISSUE THREAD

**Issue by stu-github** [infrastlabs/docker-headless#19]
docker run -it --rm --net=host --shm-size 1g -e VNC_OFFSET=99 \
  --tmpfs /run --tmpfs /run/lock --tmpfs /tmp -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
  --cap-add SYS_BOOT --cap-add SYS_ADMIN infrastlabs/docker-headless:gnome

connect with mRemoteNG-1.76.20

can't copy/paste files.

How to fix it?

**Comment by huapox** [comment]
with `--privileged`

```
docker run -it --rm --net=host --shm-size 1g -e VNC_OFFSET=99 \
  --tmpfs /run --tmpfs /run/lock --tmpfs /tmp -v /sys/fs/cgroup:/s/fs/cgroup:rw \
  --cap-add SYS_BOOT --cap-add SYS_ADMIN --privileged infrastlabs/docker-headless:gnome
```
