### ISSUE TITLE
RDP本地磁盘映射无法映射成功

### ISSUE THREAD

**Issue by Leo-zhanglj** [infrastlabs/docker-headless#3]
您好，
我在测试的过程中，docker采用了端口映射的方式，docker语句如下
docker run -it --name wps4-docker --rm --shm-size 1g -e VNC_OFFSET=20 -e L=zh_CN -p 50089:10089 -p 50081:10081 -p50022:10022 infrastlabs/docker-headless:full

在做本地磁盘映射的过程中，发现无法生效，截图如下，不知是否可以帮忙确认一下，是我端口映射的网络模式影响了还是其他的问题，谢谢。

![image](https://user-images.githubusercontent.com/18610058/156140526-ef735ebe-a951-4e59-92eb-f3afd01bf314.png)
![image](https://user-images.githubusercontent.com/18610058/156140613-48667918-f69f-46da-a21b-ae3b4e219b53.png)

**Comment by huapox** [comment]
可能是有端口转发， --net=host试试先；
---
另：每次连接要正常关闭才行。如已有连接， 或上次rdp异常断开： 新的rdp连接会等很久、同时挂盘、剪切版不可用

**Comment by Leo-zhanglj** [comment]
> ## 可能是有端口转发， --net=host试试先；
> 另：每次连接要正常关闭才行。如已有连接， 或上次rdp异常断开： 新的rdp连接会等很久、同时挂盘、剪切版不可用

验证结果：当前镜像版本无法实现上述功能。

**Comment by huapox** [comment]
![图片](https://user-images.githubusercontent.com/6138651/157037175-d5677e2f-38e4-4a58-a2cd-0bb115bde946.png)

`docker run -it --rm --privileged --shm-size 1g -e VNC_OFFSET=20 -e L=zh_CN --net=host infrastlabs/docker-headless`

请指定 `--privileged`

**Comment by Leo-zhanglj** [comment]
> ![图片](https://user-images.githubusercontent.com/6138651/157037175-d5677e2f-38e4-4a58-a2cd-0bb115bde946.png)
> 
> `docker run -it --rm --privileged --shm-size 1g -e VNC_OFFSET=20 -e L=zh_CN --net=host infrastlabs/docker-headless`
> 
> 请指定 `--privileged`

验证测试结果依然无法映射成功
