### ISSUE TITLE
请问一下，debian下如何让fcitx在全局生效？

### ISSUE THREAD

**Issue by Leo-zhanglj** [infrastlabs/docker-headless#4]
测试发现fcitx无法全局在应用中生效，linux的一些环境变量设置都无法工作。谢谢

**Comment by Leo-zhanglj** [comment]
resolved

**Comment by huapox** [comment]
新版 `infrastlabs/docker-headless:sogou` 搜狗输入法，是基于fcitx平台的

- https://github.com/infrastlabs/docker-headless/blob/dev/ubt-custom/src/Dockerfile.sogou#L92

```bash
sed -i "s/ibus/fcitx/g" /etc/profile; 
```
