### ISSUE TITLE
关于docker-healess镜像构建过程中的原始镜像dockerfile咨询

### ISSUE THREAD

**Issue by Leo-zhanglj** [infrastlabs/docker-headless#5]
作者您好，
看到docker-healess项目中的dockerfile有引用了其他几个镜像，

FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:xfce-deb9-v1 as loc
FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:compile-v1 as xrdpbin
FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/novnc-audio:bcs as bcs
FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/docker-headless:box07-slim as box07

请问上述几个镜像是否有对应的dockerfile可以查看学习一下？

**Comment by huapox** [comment]
https://github.com/infrastlabs/docker-headless/blob/dev/src/Dockerfile.compile

**Comment by huapox** [comment]
见新版(基于ubuntu20.04): https://github.com/infrastlabs/docker-headless/blob/dev/deb10/src/Dockerfile.compile
