### ISSUE TITLE
构建镜像时编译pulseaudio-module-xrdp的问题

### ISSUE THREAD

**Issue by Leo-zhanglj** [infrastlabs/docker-headless#6]
作者您好，

我按照https://github.com/infrastlabs/docker-headless/blob/dev/src/Dockerfile.compile这个部分的dockerfile重新构建一次镜像，发现
RUN cd /opt && git clone https://github.com.cnpmjs.org/neutrinolabs/pulseaudio-module-xrdp.git已经无法获取到代码了，我去
https://github.com/neutrinolabs/pulseaudio-module-xrdp/archive/refs/tags/v0.6.tar.gz这里去下载源代码按照dockerfile构建报错如下，是不是您构建的这个版本跟现在的版本变化较大了？
谢谢。

checking whether make sets $(MAKE)... (cached) yes
checking for LIBPULSE... yes
configure: WARNING: PULSE_DIR may not be valid - can't find expected file
configure: PULSE_CONFIG_DIR not defined
checking Searching for config.h under PULSE_DIR... find: '/opt/pulseaudio-': No such file or directory
no
configure: error: Can't find config.h under PULSE_DIR. Define PULSE_CONFIG_DIR?
pulseaudio ver: 10.0
make: *** No targets specified and no makefile found.  Stop.
The command '/bin/sh -c wget https://github.com/neutrinolabs/pulseaudio-module-xrdp/archive/refs/tags/v0.6.tar.gz; tar -zxf v0.6.tar.gz; cd /opt/pulseaudio-module-xrdp-0.6 && ./bootstrap && ./configure PULSE_DIR="/opt/pulseaudio-${pulseaudio}";   pulseaudio=$(pulseaudio --version | awk '{print $2}') && echo "pulseaudio ver: $pulseaudio" &&   cp -a /opt/pulseaudio-${pulseaudio}/config.h . && cp -a /opt/pulseaudio-${pulseaudio}/src/pulsecore/ .;   make &&   cd /opt/pulseaudio-module-xrdp/src/.libs &&   install -t "/var/lib/xrdp-pulseaudio-installer" -D -m 644 *.so;' returned a non-zero code: 2
[root@docker229 headless-linux]#

**Comment by huapox** [comment]
见新版(基于ubuntu20.04): https://github.com/infrastlabs/docker-headless/blob/dev/deb10/src/Dockerfile.compile
