### ISSUE TITLE
没声啊。。。 另外 sogou拉不下来

### ISSUE THREAD

**Issue by homuraLan** [infrastlabs/docker-headless#7]
是要开什么东西吗，麻烦教教我，另外桌面图标怎么开？ docker-compose.yml 部署的 
![image](https://user-images.githubusercontent.com/96775034/223179263-c6a4374b-dc56-4f3a-a8d0-f754174c6760.png)

![image](https://user-images.githubusercontent.com/96775034/223180259-f0fd7d7b-6f39-45f2-9548-2c3d6a7578d1.png)

**Comment by huapox** [comment]
要开个音频有才声音的， 开音频后也可用mstsc连接测试声音（连接选项勾上声音），后者无声音延迟，音效更好

**Comment by huapox** [comment]
命令行： `play ~/*.mp3` HOME目录有一首铃声

**Comment by huapox** [comment]
sogou镜像拉取为网络问题，可换机换网改加速器重试下
