### ISSUE TITLE
novnc怎么启用多个会话

### ISSUE THREAD

**Issue by 350227036** [infrastlabs/docker-headless#8]
访问 http://192.168.14.249:10081/vnc/后只有两个会话可以选。

![Snipaste_2023-05-16_10-18-42](https://github.com/infrastlabs/docker-headless/assets/25679758/b2a00916-dddd-4975-aea6-facfdbe519ae)

**Comment by huapox** [comment]
你好， 考虑简洁性，新版(Ubuntu20.04)是拆分为独立实例的了（不同DE各一份桌面对应一份Xorg/xrdp/novnc，VNC登陆页对应完整版/lite版两个入口）

vnc多会话：

- 首先，多会话/多桌面不对应于单个容器（考虑容器体积及容器内进程简洁）
- x11网关模式：可参考Debian9旧版 https://github.com/infrastlabs/docker-headless/blob/box09/DE/docker-compose.yml (多桌面/多DE环境。 由x11网关开多个Xorg实例，之后不同DE连上来 DE跑在不同容器上的)
- TODO: 新版考虑多个容器的互通 基于chisel做socket隧道代理，以达成某个vnc桌面做入口可访问其它实例的目的。待实现

**Comment by huapox** [comment]
x11网关模式：已废弃， 版本变更参考：https://github.com/infrastlabs/docker-headless/blob/dev/Changelog.md

**Comment by 350227036** [comment]
> 你好， 考虑简洁性，新版(Ubuntu20.04)是拆分为独立实例的了（不同DE各一份桌面对应一份Xorg/xrdp/novnc，VNC登陆页对应完整版/lite版两个入口）
> 
> vnc多会话：
> 
> * 首先，多会话/多桌面不对应于单个容器（考虑容器体积及容器内进程简洁）
> * x11网关模式：可参考Debian9旧版 https://github.com/infrastlabs/docker-headless/blob/box09/DE/docker-compose.yml (多桌面/多DE环境。 由x11网关开多个Xorg实例，之后不同DE连上来 DE跑在不同容器上的)
> * TODO: 新版考虑多个容器的互通 基于chisel做socket隧道代理，以达成某个vnc桌面做入口可访问其它实例的目的。待实现

------------------------------------------------------------
感谢您 的回复，我的需求场景是创建一个云桌面容器，让40个学生连上去，每个人有自己的桌面会话。在自己的会话里打开 开发工具进行编程的学习。因为服务器硬盘空间的问题，所以我想只在一个容器里安装开发环境。让所有学生在上面操作。我使用了旧版本21.7.14(tag:box06)镜像，发现只有第一个会话可以进入，其他会话进入后是黑屏

**Comment by huapox** [comment]
> 其他会话进入后是黑屏

再之前的版本也是X11网关模式， 需要额外启DE环境注册上对应的XServer才有界面的， 你可参考我前面给的docker-compose.yml链接（对应外置启多个容器）。

单个容器内开多份 真心不推荐。 （太重：还不如装一套正规的如Ubuntu桌面系统, 然后基于多用户Session来远程登陆， 不过对于40个用户规模来说单机资源估计够呛）

**Comment by 350227036** [comment]
> > 其他会话进入后是黑屏
> 
> 再之前的版本也是X11网关模式， 需要额外启DE环境注册上对应的XServer才有界面的， 你可参考我前面给的docker-compose.yml链接（对应外置启多个容器）。
> 
> 单个容器内开多份 真心不推荐。 （太重：还不如装一套正规的如Ubuntu桌面系统, 然后基于多用户Session来远程登陆， 不过对于40个用户规模来说单机资源估计够呛）


感谢您的解答
