### ISSUE TITLE
请问如何隐藏这个dock图标

### ISSUE THREAD

**Issue by Leo-zhanglj** [infrastlabs/docker-headless#9]

**Comment by Leo-zhanglj** [comment]
图片上传不了，就是桌面上的dock隐藏掉，比如点一下固定在dock上前面的对号就隐藏掉某也应用了，如何能全部用命令在dockerfile中隐藏掉，谢谢。

**Comment by huapox** [comment]
![图片](https://github.com/infrastlabs/docker-headless/assets/6138651/18672333-bd18-4222-82e7-e397def8cf71)

如图删除对应项即可

**Comment by huapox** [comment]
`/home/headless/.config/plank/dock1/launchers/`
